title: Granja Mandrágora
author:
  name: Joan Navarrete                       # Default author name
  email: contacto@granjamandragora.es                   # Default author email
  copyright: "Copyright 2018 Granja Mandrágora. Todos los derechos reservados"

# Logo must be uploaded to theme's img folder.
logo: logo_bn_pq.png
header:
  title: Permacultura Mediterránea
  description: Granja Mandrágora es un proyecto regido por los principios de la permacultura que aspira a demostrar que otro modo de vida es posible.

  background: 'abejas_en_cuadro.jpg'
#  buttons:
#    - text: Seguir Explorando
#      url: "#home_posts"
#      class: button radius

social:
  - url: 'https://twitter.com/getgrav'
    icon: 'twitter'
  - url: 'https://www.facebook.com/granjamandragora/'
    icon: 'facebook'
  - url: 'http://www.vimeo.com'
    icon: 'vimeo-square'
  - url: 'https://www.pinterest.es/mandragorafarm/'
    icon: 'pinterest'

taxonomies: [category,tag,featured]                  # Arbitrary list of taxonomy types
blog:
  route: '/blog'                            # Route to blog
metadata:
    description: 'Granja Mandrágora'             # Site description
summary:
  size: 300                                 # Maximum length of summary (characters)
routes:
  /something/else: '/blog/sample-3'         # Alias for /blog/sample-3
  /another/one/here: '/blog/sample-3'       # Another alias for /blog/sample-3
  /new/*: '/blog/*'                         # Wildcard any /new/my-page URL to /blog/my-page Route

footer:
  widget:
    title: Sobre Granja Mandrágora
    description: Granja Mandrágora es un proyecto regido por los principios de la permacultura que aspira a demostrar que otro modo de vida es posible.
    link:
copyright: ""
